apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    insecure-skip-tls-verify: true
    server: "http://k8sdnsranchernode-611651171.eu-central-1.elb.amazonaws.com:8080/r/projects/1a7/kubernetes:6443"
  name: "demo-kubernetes-env"
contexts:
- context:
    cluster: "demo-kubernetes-env"
    user: "demo-kubernetes-env"
  name: "demo-kubernetes-env"
current-context: "demo-kubernetes-env"
users:
- name: "demo-kubernetes-env"
  user:
    token: "QmFzaWMgUTBKRlJrVTNORUpGTWpWQlFrRkZNRGsxTlVNNmRWWjRUSGxFWjNnMVVqWnRRMVJJV0hsV1oxbGpVWGRaWWtWTlVGSnZWVzAxVFhKVFJFNUdaUT09"
